create table cart (id integer not null, soluong integer not null, productid nvarchar(20), uid nvarchar(20), primary key (id)) engine=InnoDB;
create table category (cateid integer not null, tenloai varchar(255), trangthai integer not null, primary key (cateid)) engine=InnoDB;
create table comment (orderid nvarchar(20) not null, pid nvarchar(20) not null, noidung varchar(255), sao varchar(255), primary key (orderid, pid)) engine=InnoDB;
create table inventory (id integer not null, height double, length double, price double, quantity int, size int, special_from_time date, special_price double, special_to_time date, weight double, width double, pid nvarchar(20), primary key (id)) engine=InnoDB;
create table order_detail (order_id nvarchar(20) not null, product_id nvarchar(20) not null, delivery_address nvarchar(20) not null, destination nvarchar(20) not null, price int not null, quantity int not null, total double not null, user_pay double not null, tid integer, primary key (order_id, product_id)) engine=InnoDB;
create table orders (orderid nvarchar(20) not null, endtime datetime not null, starttime datetime not null, state int not null, total double not null, uid nvarchar(20), primary key (orderid)) engine=InnoDB;
create table permisson (roleid integer not null, describes nvarchar(20) not null, name nvarchar(20) not null, state int not null, primary key (roleid)) engine=InnoDB;
create table permissons (roleid integer not null, typeid integer not null, primary key (roleid, typeid)) engine=InnoDB;
create table product (pid nvarchar(20) not null, images json, info nvarchar(20) not null, likes int, product_name nvarchar(20) not null, state int, views int, cateid integer, primary key (pid)) engine=InnoDB;
create table transport (tid integer not null, fee double not null, name nvarchar(50) not null, primary key (tid)) engine=InnoDB;
create table type_member (typeid bigint not null auto_increment, state int not null, type_name nvarchar(50) not null, primary key (typeid)) engine=InnoDB;
create table userdetail (uid nvarchar(20) not null, address nvarchar(100), birthday datetime, firstname nvarchar(20), gmail nvarchar(20), lastname nvarchar(20), phone nvarchar(20), state int, timestamp datetime not null, typemember_id bigint, primary key (uid)) engine=InnoDB;
create table account (uid bigint not null, email nvarchar(20) not null, passwd nvarchar(20) not null, state int not null, primary key (uid)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
alter table cart add constraint FKkh5di77cfr01hq05rbcogspec foreign key (productid) references product (pid);
alter table cart add constraint FK90otqnshmdhn7vdp5iyd9m4k5 foreign key (uid) references userdetail (uid);
alter table comment add constraint FKpj65tlc6ss64rdq5i5ttcxd6b foreign key (orderid) references orders (orderid);
alter table comment add constraint FKa56s692b15h8wwlcx38qurure foreign key (pid) references product (pid);
alter table inventory add constraint FKc5jhtxatbxxpqsf2pp88a7vej foreign key (pid) references product (pid);
alter table order_detail add constraint FKrws2q0si6oyd6il8gqe2aennc foreign key (order_id) references orders (orderid);
alter table order_detail add constraint FKb8bg2bkty0oksa3wiq5mp5qnc foreign key (product_id) references product (pid);
alter table order_detail add constraint FKp5ioeh5elu7snkylx05lmr06l foreign key (tid) references transport (tid);
alter table orders add constraint FK28r72ha9jlmafkuu7i5a0my2v foreign key (uid) references userdetail (uid);
alter table product add constraint FKt3b224xjwuefm2m3hhfxwp067 foreign key (cateid) references category (cateid);
alter table userdetail add constraint FKnbditvl38kaai5v11fe5f9w49 foreign key (typemember_id) references type_member (typeid);
